### ISSUE TITLE
다음과 같은 버그가 있어요

### ISSUE THREAD

**Issue by puresprout** [texcoaster/py-BingoGame#1]
![스크린샷 2022-09-21 오전 9 58 14](https://user-images.githubusercontent.com/10364496/191390958-657981e0-e43f-4d99-9280-db2c36d0534a.png)

승리했을때 4개가 안된 돌까지 색깔이 칠해져요

**Comment by texcoaster** [comment]
고칠게요!

**Comment by texcoaster** [comment]
고쳤습니다!!
